### ISSUE TITLE
MoneyField breaks Admin List view for prices with certain currencies

### ISSUE THREAD

**Issue by graik** [django-money/django-money#196] opened 2016-05-13 19:16 UTC
I included a standard money field in the Admin list view.
models.py:

```
    price = MoneyField('Unit price', max_digits=8, decimal_places=2, 
                       default_currency='USD',
                       blank=True, null=True, 
                       help_text = 'cost per unit (!)')
```

admin.py:
`list_display = ('product',  'Status', 'show_quantity',  'price' )
`
This works for the default USD prices but it breaks as soon as I add, e.g. a Saudi Riyal price. The problem seems to be that the admin view interprets MoneyField as a DecimalField and then tries to format o.price as a decimal number whereas the string actually already contains the arabic currency symbol.:

> File "/data/raik/py/labhamsterdjango/venv/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 231, in items_for_result
>   result_repr = display_for_field(value, f, empty_value_display)
> File "/data/raik/py/labhamsterdjango/venv/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 399, in display_for_field
>   return formats.number_format(value, field.decimal_places)
> File "/data/raik/py/labhamsterdjango/venv/local/lib/python2.7/site-packages/django/utils/formats.py", line 181, in number_format
>   force_grouping=force_grouping
> File "/data/raik/py/labhamsterdjango/venv/local/lib/python2.7/site-packages/django/utils/numberformat.py", line 38, in format
>   int_part, dec_part = str_number.split('.')

Workaround:
defining a custom show_price method prevents this:

admin.py:

```
    list_display = ('product',  'Status', 'show_quantity', 'show_price',)
    def show_price(self, o):
        """Workaround for bug in djmoney -- MoneyField confuses Admin formatting"""
        if not o.price:
            return u''
        return unicode(o.price)
```

**Comment by graik** [comment] 2016-05-13 19:26
PS: settings.py:
``
LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Riyadh')
USE_I18N = True
USE_L10N = False  ## de-activate automatic localization of numbers and dates
``
The problem is related to the USE_L10N setting. If I set it to `True` the bug disappears. But USE_L10N=True has some *very* weird side effects -- namely the django admin templates revert to an older style, the date format becomes very verbose etc.

**Comment by Stranger6667** [comment] 2017-03-07 14:10
Hi @graik !
The issue should be fixed now in the master branch. Could you check, please, if the problem is solved?

**Closed** 2017-07-10 17:57 UTC
Labels: bug, duplicate

**Comment by omargawdat** [comment] 2024-10-21 07:12
django: 5.1
money: 3.5.3
<img width="527" alt="image" src="https://github.com/user-attachments/assets/17b8cbde-80dd-48e0-a249-169a3bd8876a">
