### ISSUE TITLE
Thousand separator added twice in some views

### ISSUE THREAD

**Issue by benjaoming** [django-money/django-money#220] opened 2016-09-13 09:45 UTC
Original post by @k8n

> Not sure if this is related or merits a separate issue ticket.
> I am seeing things like "9,,999.99" in admin changelists (note the double comma).
> I have this in settings.
> 
> ```
> USE_L10N = True
> USE_THOUSAND_SEPARATOR = True
> ```
> 
> Admin treats MoneyField field as a DecimalField and applies L10N formatting on top of the already-formatted value. Essentially the following happens:
> 
> ```
> from django.utils import formats
> ...
> formats.number_format(field, decimal_places)
> ...
> ```
> 
> See https://github.com/django/django/blob/master/django/contrib/admin/utils.py#L413.

To make it easier to solve this, it would be nice to know exactly which places you see the double comma @k8n?

https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-USE_THOUSAND_SEPARATOR

**Comment by k8n** [comment] 2016-09-15 02:32
@benjaoming thanks.

Workarounds for this issue are plenty, of course. It's just that a double-comma doesn't look right as the default behaviour.

The issue is apparent wherever django admin renders a naked `MoneyField` when both `USE_THOUSAND_SEPARATOR` and `USE_L10N` are `True`. That happens, for example, when viewing a model's change list in admin.

admin's `display_for_field()` method treats `MoneyField` as a `DecimalField` and calls `number_format()` on it. Both `number_format()` and MoneyField's `__unicode__()` do localization formatting.

I couldn't yet think of a simple / clever solution that would be backward-compatible.

I looked at the use of the `use_l10n` property on the `MoneyPatched` class in hopes to control this localization behaviour. It seems that in this context, the value of `use_l10n` makes no difference to the output.

Trouble is too, even if it worked, `use_l10n` cannot be conveniently set. It may be nice to have `MoneyField`'s constructor pass this property to `MoneyPatched` somehow.

Here is more of an example of this behaviour in django's shell:

```
from django.conf import settings
from django.db import models
from djmoney.models.fields import MoneyField
from djmoney.models.fields import Money
from django.utils import formats
from django.contrib.admin.utils import display_for_value

settings.USE_L10N = True
settings.USE_THOUSAND_SEPARATOR = True

class A(models.Model):
    m = MoneyField()
    class Meta:
        app_label = "test"

a = A()
a.m = Money(1234) 
formats.number_format(a.m, 2)  # returns u'1,,234.00'

a.m.use_l10n = False
formats.number_format(a.m, 2)  # returns u'1,,234.00'

settings.USE_L10N = False
formats.number_format(a.m, 2)  # returns u'1,234.00'

settings.USE_L10N = True
display_for_field(a.m, a._meta.get_field('m'), 0)  # returns u'1,,000.00 XYZ'
```

**Comment by benjaoming** [comment] 2016-09-18 20:28
Thanks for elaborating this!

> I couldn't yet think of a simple / clever solution that would be backward-compatible.

IMO solving the issue would trump the goal of being backwards-compatible with possible work-arounds. But *if* there is a way to do both, it's worth making an extra effort.

If it's backwards incompatibe, it's also completely fair to write this in release notes. We could also bump the minor version number to signal the change. E.g. release it as 0.10.

**Comment by Stranger6667** [comment] 2016-09-25 08:26
My 2 -,
We currently use localization from ``py-moneyed`` in ``MoneyPatched.__unicode__``. But ``django-admin`` (and probably many more apps) doesn't know anything about ``MoneyField`` way of localization and uses one from ``django``.
So, this combination leads to very strange results. I think, that we can do this:

1. Don't use localization in `__unicode__`.
2. Create separate method for localization in ``MoneyPatched``
3. Update localization tags accordingly

But in this way we will lose currency signs in the admin. On the other side representation will be handled as normal decimal value without localization (and bugs).

Also, there is another way - inspect stack, but it is too hackish IMO. Or patch admin classes in runtime.

Anyway admin integration is out weak spot and it should be fixed.

P.S. Correct me if I'm wrong, but localization feature was introduced for template tag, right? Was it a side-effect, that it affects values displaying in the admin?

**Comment by Stranger6667** [comment] 2016-09-25 08:38
Related issues - #196, #154 , #90, #102 #72, #63, #203 
Everything is about localization / formatting

**Comment by k8n** [comment] 2016-09-26 01:59
@Stranger6667, I agree with your point on use of localization in `__unicode__` (i.e. it should not be dene there).

I will also note that the current implementation may lead to inconsistent unicode representations representation with respect to `moneyed`.

E.g.

```
from django.conf import settings
from django.db import models
from djmoney.models.fields import MoneyField
from djmoney.models.fields import Money

import moneyed

settings.USE_L10N = True
settings.USE_THOUSAND_SEPARATOR = False

class A(models.Model):
    m = MoneyField()
    class Meta:
        app_label = "test"

n = Money(1234, moneyed.EUR)
print unicode(n)  # outputs: 1,234.00 €

a = A()
a.m = n
print unicode(a.m)  # outputs: 1,234.00 EUR

```

I see this inconsistency in django where, for example, in templates I output both MoneyFields and moneyed calculations.

**Comment by Stranger6667** [comment] 2017-03-07 14:10
Hi @k8n!
The issue should be fixed now in the master branch. Could you check, please, if the problem is solved?

**Closed** 2017-07-10 17:56 UTC
Labels: bug, duplicate
