### ISSUE TITLE
Setting readonly on a field in django admin displays wrong data

### ISSUE THREAD

**Issue by adi-** [django-money/django-money#334] opened 2017-09-10 18:44 UTC
Django admin displays price as: `123,45 EUR,00` – it adds `,00` to the string

**Comment by Stranger6667** [comment] 2017-09-10 19:26
Hello @adi-!
Could you, please, specify Python, Django and django-money versions you're using? We had a few similar issues and they should be fixed in master branch

**Comment by adi-** [comment] 2017-09-10 19:31
Python 3.5.2
Django 1.11.4
django-money 0.11.4

**Comment by Stranger6667** [comment] 2017-09-10 20:11
Could you, please, check if the issue exists in latest django-money version from master branch?

**Comment by adi-** [comment] 2017-09-10 20:32
Not fixed :(

**Comment by Stranger6667** [comment] 2017-09-10 20:34
So, I'll investigate the issue tomorrow :) thank you for the bug report

**Comment by adi-** [comment] 2017-09-10 20:36
Np! I can help to test the fix when you spot the problem

**Comment by adi-** [comment] 2017-09-11 16:42
LANGUAGE_CODE = 'pl'
USE_L10N = True

py-moneyed 0.7.0
No custom _FORMATTER

field in `model.py`: `price = MoneyField('Cena', max_digits=10, decimal_places=2, default_currency='PLN')`

**Comment by Stranger6667** [comment] 2017-09-12 09:51
I reproduced the issue with the following behaviour
<img width="1413" alt="2017-09-12 11 49 49" src="https://user-images.githubusercontent.com/1236561/30319581-8e6c3896-97b0-11e7-9ecb-5536d1bb30ae.png">

I'll work on the fix today

**Comment by Stranger6667** [comment] 2017-09-12 10:05
Our approach to fix this issue before is to patch some modules in runtime, in ``djmoney.apps.MoneyConfig.ready``. 

But if problematic function (``display_for_field``) will be imported before this patch, then it will not be patched in this module, where was imported. Thus being said in the worst case we can't guarantee, that our patching will cover all imports - for example if you'll import ``display_for_field`` in your code, that is loaded before ``djmoney``, then you'll use not patched version we can't detect it automatically.

Consequently, ``django.contrib.admin.templatetags.admin_list`` could also be affected, because it imports ``display_for_field``. Anyway, I'll push the fix in a few minutes.

**Closed** 2017-09-22 06:14 UTC
Labels: bug
