### ISSUE TITLE
Django 1.8?

### ISSUE THREAD

**Issue by psnma** [django-money/django-money#113] opened 2015-04-03 17:35 UTC
I'm trying to use with Django 1.8 and...
```
Traceback (most recent call last):
from django.db.models.sql.expressions import SQLEvaluator
ImportError: No module named expressions

**Comment by edwinlunando** [comment] 2015-04-05 11:30
Django 1.8 remove that expressions.py file. Anyone had any idea the API replacement?

**Comment by mpampols** [comment] 2015-04-06 10:37
I think that this fix from django-bitfield may give an idea: https://github.com/greyside/django-bitfield/commit/8e515152bb2c6cfd772c9cc04bfeac51c50389fa

**Comment by edwinlunando** [comment] 2015-04-14 08:08
There is something like this https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#converting-values-to-python-objects

**Comment by edwinlunando** [comment] 2015-04-19 03:43
@mpampols do you think the problem is fixed by removing the SQLEvaluator? I will send a pull request for this.

**Comment by mpampols** [comment] 2015-04-21 11:19
@edwinlunando Yes, but I see that @pedrorodriguesgomes already sent one: https://github.com/jakewins/django-money/pull/114 (I'll try that asap. Django newbie here, sorry ;)

**Comment by nueverest** [comment] 2015-04-25 04:48
any idea when this will be fixed?

**Comment by benjaoming** [comment] 2015-04-25 09:58
@nueverest header over in #114, notice that there is a lack of input, maybe chip in a bit on that one, and we could be well on the way :)

**Comment by auvipy** [comment] 2015-06-13 17:51
so is django money 1.8 ready?

**Comment by benjaoming** [comment] 2015-06-13 20:45
yeah should be, tagged a new 0.7.0, @reinbach could you do the pypi again? :)

**Comment by enono78** [comment] 2015-06-14 07:45
@reinbach could you do the pypi again? :+1:

**Comment by reinbach** [comment] 2015-06-14 10:30
@enono78 @benjaoming pypi has been updated

**Comment by benjaoming** [comment] 2015-06-14 10:36
fantastic!

**Closed** 2015-09-19 20:38 UTC
