### ISSUE TITLE
Currency symbol not visible for some currencies in Django Admin

### ISSUE THREAD

**Issue by eriktelepovsky** [django-money/django-money#102] opened 2015-01-03 10:17 UTC
Currency symbol is not visible for some currencies (for example PLN or EUR).

See django admin screenshot attached:
![money_formatter](https://cloud.githubusercontent.com/assets/2685808/2840969/7f439f10-d05f-11e3-883c-51dc80556870.png)

Expected behaviour:
![image](https://cloud.githubusercontent.com/assets/2685808/5602144/d47e216a-9339-11e4-8ce1-98c1e19926f6.png)

I think, it is a unicode bug, because this workaround works (but it disables ordering):

``` python
def price_unicode(self, obj):
    return u'%s' % obj.price
```

Tested with both `USE_L10N = True` and `False` as well.

**Comment by jplehmann** [comment] 2016-12-31 20:24
@eriktelepovsky would appreciate some guidance. I cannot seem to get the currency symbol/prefix/sign to render in any other way than by using `format_money(Money(10, EUR))`. If I simply render the field (``{{ ad.price }}``), even using your `price_unicode` wrapper, or using money localize (` {% money_localize '10' 'EUR' %}`), I simply get "10 EUR" without the sign. I'm guessing the latter doesn't work because it's not using the `DEFAULT` locale, which seems to be necessary to access all the symbols in https://github.com/limist/py-moneyed/blob/master/moneyed/localization.py.

Maybe I'm being dense, but it seems like this merits some additional treatment in the README, as I have spent quite a bit of time trying to understand this.

**Comment by jplehmann** [comment] 2017-01-01 14:01
I confirmed that the issue was locale. For some reason, the `en_US` locale doesn't like to show currency symbols. Programmatic formatting with `DEFAULT` locale produced the symbols.

**Comment by eriktelepovsky** [comment] 2017-01-03 16:52
Hi @jplehmann and thank you for your investigation. So what is the final conclusion for this issue? What is necessary to be done to show unicode currency symbols in the admin?

**Comment by jplehmann** [comment] 2017-01-07 16:29
Hi Erik, unfortunately it looks like my problem was orthogonal to yours. I couldn't get symbols to display anywhere (at first), but it was only because my locale wasn't set to `DEFAULT`.

Now, looking at my admin, I still have the same problem which you did.  That is, I've put no special handling into rendering the currency field, and Euros and Pounds shows up without any symbol (except for US currency, which show $).

**Comment by Stranger6667** [comment] 2017-03-07 14:12
Hi @eriktelepovsky and @jplehmann  !
The issue should be fixed now in the master branch. Could you check, please, if the problem is solved?

P.S. For Django < 1.7 you could use the following snippet as on-start-up code:

```python
from djmoney.admin import setup_admin_integration

setup_admin_integration()
```

**Closed** 2017-07-10 17:58 UTC
Labels: bug, duplicate
