### ISSUE TITLE
Formatting error with django admin's list_display

### ISSUE THREAD

**Issue by arthurk** [django-money/django-money#90] opened 2014-08-20 12:26 UTC
When USE_L10N is enabled and a MoneyField is put into django admin's list_display, the already formatted value is formatted again, resulting in strings like `50,00 SEK,00`

**Comment by mstarostik** [comment] 2016-07-15 13:48
Well, I can reproduce it and it seems to be locale dependent.
e.g. with 
USE_L10N = True
LANGUAGE_CODE = 'de-de'

3.33 € will show as "3,33 €,00"

but with
USE_L10N = True
LANGUAGE_CODE = 'de-ch'

3.33 € will show as "3,33"

The first example is totally broken, the latter lacks the currency.  Now I don't know whether the bug is in django-money or in py-moneyed.  But maybe the above helps you reproduce.

**Comment by Stranger6667** [comment] 2016-07-15 13:59
@mstarostik 
Thank you for the report! Please, can you tell Django & Python versions for this example?

**Comment by Stranger6667** [comment] 2016-07-15 14:02
Ok, I got it on Python 3.5 and Django 1.9. The same situation is for read only fields in admin forms

**Comment by mstarostik** [comment] 2016-07-15 14:03
Python 3.4.3
Django 1.9.5
django-money 0.8
py-moneyed 0.6.0

**Comment by Stranger6667** [comment] 2016-07-15 14:27
Yes, this problem related to ``MoneyPatched``, so it is definitely a bug in django-money

**Comment by mstarostik** [comment] 2016-07-15 14:31
Workaround like of the one in #196 helps.

**Comment by Stranger6667** [comment] 2016-07-15 14:33
Please, what is the desired representation with given settings? I'll create a tests to cover these issues

**Comment by mstarostik** [comment] 2016-07-15 15:08
Oh well, looking further into moneyed, it seems to be more complex than I thought ;-) it doesn't seem to honour the locale's decimal/thousand separators, but instead ties those to its own locale definitions.

I'd personally expect the formatting to use the system's / app's locale setting to determine the decimal and thousand separators and the same locale's setting to place the currency symbol.

So, for LANGUAGE_CODE = de-de that would be
X.XXX,XX € or X.XXX,XX $
While LANGUAGE_CODE = en-us should yield
€X,XXX.XX or $X,XXX.XX

That does differ to what moneyed does as it ties the symbol placement to a combination of locale and currency.  But if you do it that way, you'd need a third field, amount, currency, and locale as the same currency can be used in different countries with totally different monetary formattings.  Just my 0,02 € or however to format that ;-)

**Comment by Stranger6667** [comment] 2017-03-07 14:13
Hi @arthurk and @mstarostik  !
The issue should be fixed now in the master branch. Could you check, please, if the problem is solved?

P.S. For Django < 1.7 you could use the following snippet as on-start-up code:

```python
from djmoney.admin import setup_admin_integration

setup_admin_integration()
```

For newer versions of Django adding `djmoney` to `INSTALLED_APPS` should be enough.

**Closed** 2017-07-10 17:59 UTC
Labels: bug, duplicate
