### ISSUE TITLE
Localizations not working

### ISSUE THREAD

**Issue by vibee** [django-money/django-money#131] opened 2015-08-29 09:06 UTC
Hi,

in settings.py, I  got:

  LANGUAGE_CODE = 'de_DE'
  TIME_ZONE = 'Europe/Berlin'
  USE_I18N = True
  USE_L10N = True
  USE_TZ = True

However, accessing a MoneyField (created with default_currency='EUR' via str(self.myModel.myMoneyField), i got ',' as thousands separator and '.' as decimal separator (which is wrong for 'de_DE'. Is this a bug in the django-money package or am I doing something wrong?

**Comment by benjaoming** [comment] 2015-09-19 23:13
Duplicate of #65

**Closed by benjaoming** 2015-09-19 23:13 UTC
