### ISSUE TITLE
Form valiadion error on MoneyField

### ISSUE THREAD

**Issue by stinovlas** [django-money/django-money#439] opened 2018-07-20 13:31 UTC
When I tried to create `ModelForm` based on my model containing `MoneyField`, I got error `Enter a list of values.` for the appropriate field.

After some debugging, it seems that problem is in that `djmoney.money.Money` is not instance of `list` or `tuple`, which creates a problem at [clean method of MultiValueField](https://github.com/django/django/blob/master/django/forms/fields.py#L1009).

Simple solution is to override clean method of `MoneyField`, but it would be great if you could address this issue in `django-money` upstream.

**Comment by Stranger6667** [comment] 2018-07-21 16:52
Hi @stinovlas !

Could you provide some example to reproduce the issue? Also Python / Django / djmoney version would be helpful

Thanks

**Comment by stinovlas** [comment] 2018-07-23 07:56
Sure, thanks for your quick response. Here are my versions:

```
Python: 3.6.5
Django: 2.0.7
django-money: 0.14.1
```

Minimal working example for application `djmoney_test`:

```python
# djmoney_test/models.py
from django.db import models
from djmoney.models.fields import MoneyField

class MyModel(models.Model):
    amount = MoneyField(max_digits=64, decimal_places=4)
```

```python
# djmoney_test/forms.py
from django import forms
from djmoney.forms.fields import MoneyField
from djmoney_test.models import MyModel

class MyModelForm(forms.ModelForm):

    amount = MoneyField(disabled=True)

    class Meta:
        fields = '__all__'
        model = MyModel
```

```python
# djmoney_test/tests.py
from django.test import TestCase
from djmoney.money import Money
from djmoney_test.forms import MyModelForm
from djmoney_test.models import MyModel

class TestMyModelForm(TestCase):
    def setUp(self):
        self.instance = MyModel(amount=Money('42.00', 'USD'))
        self.instance.save()

    def test_valid_form(self):
        form = MyModelForm(data={}, instance=self.instance)
        self.assertEqual(form.errors, {})
        self.assertTrue(form.is_valid())
```

```python
# settings.py
SECRET_KEY = 'whatever'

INSTALLED_APPS = [
    'djmoney',
    'djmoney_test',
]

DATABASES = {
        'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': ':memory:'}
}
```

Just generate migrations and run tests with `django-admin`.

**Comment by Stranger6667** [comment] 2018-07-23 10:09
Thank you for the provided info :) The issue is fixed in upstream, I believe we'll issue a new release in the next few days

**Closed** 2018-07-23 10:08 UTC
Labels: bug

**Comment by stinovlas** [comment] 2018-07-23 11:09
Thank you very much :-).

**Comment by benjaoming** [comment] 2018-07-23 13:21
0.14.2 is released! :)
