### ISSUE TITLE
MoneyWidget returns None by default

### ISSUE THREAD

**Issue by djsan15** [django-money/django-money#212] opened 2016-07-21 07:27 UTC
MoneyWidget should return the default value specified in the model as the 'amount' instead of 'None'. 
This causes an issue while saving the model from django admin because we have to always input a default value as 'None' is not accepted by the model.

Essentially a small change is required in '/djmoney/forms/widgets.py':
- 'decompress' method should "return [self.default, self.default_currency]" or "return [0, self.default_currency]" instead of "return [None, self.default_currency]"

**Comment by Stranger6667** [comment] 2016-07-21 07:33
Hello, @djsan15 !
Could you provide a test case for your situation, please?

**Comment by djsan15** [comment] 2016-07-21 07:45
For example, 
My Model is-
````
class xyz(models.Model):
    credit=MoneyField(max_digits=10, decimal_places=2, default=0,default_currency='INR')
````
Now when I try to save through Django Admin after editing any other field in XYZ, then the form submissions fails and it says.. "Credit field is required" although I have specified a default value as 0. This is because the MoneyWidget returns None instead of 0.

**Comment by Stranger6667** [comment] 2016-07-21 08:53
Did you try to add ``blank=True`` to the field?
According to [Django documentation](https://docs.djangoproject.com/en/1.9/ref/models/fields/#blank):

> If a field has blank=True, form validation will allow entry of an empty value. If a field has blank=False, the field will be required.

**Comment by djsan15** [comment] 2016-07-21 08:58
I want the default value to be 0 not None. That is the reason I have added 'default=0' in credit field.

**Comment by Stranger6667** [comment] 2016-07-21 09:05
So, the problem is, that when you're added ``blank=True`` you got ``None`` as a default instead of ``0``?

**Comment by djsan15** [comment] 2016-07-21 09:19
Yes, I need 0 as the default value for amount

**Comment by Stranger6667** [comment] 2016-07-21 09:48
OK, thank you for the report!
I'll investigate the issue today and probably it will be fixed soon.

**Comment by djsan15** [comment] 2016-07-21 09:59
Thanks.

**Comment by Stranger6667** [comment] 2017-02-23 14:29
I can't reproduce the issue with Python 2.7.13 & Django 1.11b1. The provided model is displayed with  0 as a default value and Indian Rupee as a currency. Saving works, because the POST data is credit: 0 credit_currency: INR and autogenerated model form works OK.

If the issue will occur, please feel free to reopen the issue.
Probably, it is just not relevant.

**Closed by Stranger6667** 2017-02-23 14:29 UTC
Labels: bug
