### ISSUE TITLE
MoneyField does not handle localization

### ISSUE THREAD

**Issue by ajaniv** [django-money/django-money#65] opened 2013-12-26 22:11 UTC
A comma within the string causes an exception to be thrown when passing the string as is to Money, which tries to create a Decimal from it.
Decimal cannot handle a string formatted as follows: 1,000
Following is the patch that was applied to fix the problem in widgets.py

def value_from_datadict(self, data, files, name):
        if name not in data:
            return None
        amount, currency = data.get(name), data.get(get_currency_field_name(name))
        if isinstance(amount, Money):
            return amount
        if isinstance(amount, str):
            amount = amount.replace(',','')
        return Money(amount=amount, currency=currency)

**Comment by Stranger6667** [comment] 2016-07-31 20:00
I'm closing this issue, because it seems to be out of date. If the problem is still here, then feel free to open new issue

**Closed by Stranger6667** 2016-07-31 20:00 UTC

**Comment by k8n** [comment] 2016-09-13 03:57
Not sure if this is related or merits a separate issue ticket.
I am seeing things like "9,,999.99" in admin changelists (note the double comma).
I have this in settings.
```
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
```
Admin treats MoneyField field as a DecimalField and applies L10N formatting on top of the already-formatted value. Essentially the following happens:
```
from django.utils import formats
...
formats.number_format(field, decimal_places)
...
```

See https://github.com/django/django/blob/master/django/contrib/admin/utils.py#L413.

**Comment by benjaoming** [comment] 2016-09-13 09:47
Hi @k8n - thanks for reporting! This issue is closed and 3 years old, so not all that relevant to post in ;)

I've opened up #220 with your text, please feel welcome to help solve it. It seems like something that could warrant some testing with different django settings enabled.
